### Numpy 

In [1]:
import numpy as np

In [6]:
# Create arrays 
# create a 1D array

arr1 = np.array([1, 2, 3, 4, 5])
print(type(arr1))
print(arr1.shape)

<class 'numpy.ndarray'>
(5,)


In [9]:
arr2 = np.array([1,2,3,4,5])

arr2.reshape(1,5)  # reshaping the array

array([[1, 2, 3, 4, 5]])

In [10]:
arr2 = np.array([[1,2,3,4,5]])

arr2.shape

(1, 5)

In [13]:
# 2D Array

arr3 = np.array([[1,2,3,4,5], [1,2,3,4,5]])
print(arr3)
arr3.shape

[[1 2 3 4 5]
 [1 2 3 4 5]]


(2, 5)

In [14]:
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

In [15]:
np.arange(0, 10, 2).reshape(5, 1)

array([[0],
       [2],
       [4],
       [6],
       [8]])

In [16]:
np.ones((3, 4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [17]:
# identity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [18]:
arr = np.array([[1,2,3],[4,5,6]])

print("Array:\n", arr)
print("Shape:", arr.shape)
print("Number of dimensions:", arr.ndim)
print("Size (number of elements):", arr.size)
print("Data type:", arr.dtype)
print("Item size (in bytes):", arr.itemsize)

Array:
 [[1 2 3]
 [4 5 6]]
Shape: (2, 3)
Number of dimensions: 2
Size (number of elements): 6
Data type: int64
Item size (in bytes): 8


In [19]:
# Numpy Vectorized operation

arr1 = np.array([1,2,3,4,5])
arr2 = np.array([10,20,30,40,50])

# element wise addition
print("Addition:", arr1 + arr2)

# Element wise substraction
print("Substraction:", arr1 - arr2)

# Element wise Multiplication
print("Multiplication:", arr1 * arr2)

# Element wise division
print("Division:", arr1 / arr2)

Addition: [11 22 33 44 55]
Substraction: [ -9 -18 -27 -36 -45]
Multiplication: [ 10  40  90 160 250]
Division: [0.1 0.1 0.1 0.1 0.1]


In [20]:
# universal functions

arr = np.array([2,3,4,5,6])

# square root
print(np.sqrt(arr))

# exponential
print(np.exp(arr))

# sine
print(np.sin(arr))

# natural log
print(np.log(arr))

[1.41421356 1.73205081 2.         2.23606798 2.44948974]
[  7.3890561   20.08553692  54.59815003 148.4131591  403.42879349]
[ 0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155 ]
[0.69314718 1.09861229 1.38629436 1.60943791 1.79175947]


In [22]:
# array slicing and indexing

arr = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print("Array : \n", arr)

Array : 
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [23]:
arr[0]

array([1, 2, 3, 4])

In [24]:
arr[0][0]

np.int64(1)

In [25]:
arr[1:, 2:]

array([[ 7,  8],
       [11, 12]])

In [27]:
arr[0:2, 1:]

array([[2, 3, 4],
       [6, 7, 8]])

In [28]:
arr[1:,1:3]

array([[ 6,  7],
       [10, 11]])

In [29]:
# modify array elements

arr[0,0] = 100 
print(arr)

[[100   2   3   4]
 [  5   6   7   8]
 [  9  10  11  12]]


In [30]:
arr[1:] = 100

In [31]:
arr

array([[100,   2,   3,   4],
       [100, 100, 100, 100],
       [100, 100, 100, 100]])

In [34]:
# Statistical Concept - Normalization

data = np.array([1, 2, 3, 4, 5])

mean = np.mean(data)
std_dev = np.std(data)

normalized_data = (data-mean) / std_dev
print("Normalized data:", normalized_data)

Normalized data: [-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


In [35]:
# Mean
mean = np.mean(data)
print("Mean:", mean)

# Median
median = np.median(data)
print("Median:", median)

# Standard Deviation
std_dev = np.std(data)
print("Standard Deviation:", std_dev)

# Variance
variance = np.var(data)
print("Variance:", variance)

Mean: 3.0
Median: 3.0
Standard Deviation: 1.4142135623730951
Variance: 2.0


In [40]:
# Logical Operation
data = np.array([1,2,3,4,5,6,7,8,9,10])

print(data[data>5])

print(data[(data>5) & (data<8)])

[ 6  7  8  9 10]
[6 7]
